server:
  port: 0

logging:
  level:
    ROOT: INFO
    
spring:
  web:
    resources:
      static-locations:
      - classpath:/dist/
      
      
#spring.banner.image:
#  location: classpath:splash.png