server:
  port: 0


spring:
  web:
    resources:
      static-locations:
      - classpath:/dist/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
        
      
      