server:
  port: 0


#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1} [%X{user}] - %m%n"
#  level:
#    ROOT: INFO



spring:
  web:
    resources:
      static-locations:
      - classpath:/dist/
      
      
#spring.banner.image:
#  location: classpath:splash.png
