package org.r1.gde.xls.generator;

import lombok.Getter;

@Getter
public enum SheetGeneratorEvent {
	
	Q100_SHEET_GENERATED, CASSIS_SHEET_GENERATED, OBJECTIFS_SHEET_GENERATED, RETENTION_SHEET_GENERATED, 
	CASSIS_SHEET_PROGRESS, Q100_SHEET_PROGRESS, OBJECTIFS_SHEET_PROGRESS, RETENTION_SHEET_PROGRESS;
	
	
	

}
